# Generated by Django 5.1.3 on 2024-11-26 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(choices=[('econom', 'Эконом'), ('lux', 'Люкс'), ('presidential', 'Президентский')], max_length=32)),
                ('price_per_night', models.IntegerField()),
                ('room_size_sqm', models.IntegerField()),
                ('payment_option', models.TextField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.clients')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.CharField(blank=True, null=True)),
                ('rating_feedback', models.CharField(blank=True, max_length=300, null=True)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
    ]
