# Generated by Django 5.1.3 on 2024-12-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='app.rooms'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.bookings'),
        ),
    ]
